/* -LICENSE-START-
 ** Copyright (c) 2016 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 **
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */

#include <include/BMDSDICameraControl.h>
#include <include/BMDSDIControlShieldRegisters.h>
#include <string.h>

namespace BMD {
  namespace {
    int camctrlMissingFinalPadding(const byte* data, int len)
    {
      const int kHdr = 4;

      if (!data || len < kHdr) {
        return 0;
      }

      int off = 0;
      while (off < len) {
        int rem = len - off;
        if (rem < kHdr) {
          return 0;
        }

        uint8_t payloadLen = data[off + 1];
        int bodyLen = kHdr + payloadLen;
        int pad = (payloadLen % 4) ? (4 - (payloadLen % 4)) : 0;
        int total = bodyLen + pad;

        if (rem > total) {
          off += total;
          continue;
        }
        if (off + rem == len && rem == total - 1) {
          return 1;
        }
        return 0;
      }

      return 0;
    }
  }

  void SDICameraControl::setOverride(bool enabled) const {
    byte regValue = regRead8(kRegCONTROL);
    if (enabled)
      regValue |= kRegCONTROL_COVERIDE_Mask;
    else
      regValue &= ~kRegCONTROL_COVERIDE_Mask;

    regWrite8(kRegCONTROL, regValue);
  }
  
  bool SDICameraControl::getOverride() const
  {
    byte regValue = regRead8(kRegCONTROL);
    return regValue & kRegCONTROL_COVERIDE_Mask;
  }


  void SDICameraControl::setMomentaryOverride(bool enabled) {
    momentaryOverride = enabled;
  }

  bool SDICameraControl::available() const { return (regRead8(kRegICARM) & kRegICARM_ARM_Mask) == 0; }

  int SDICameraControl::read(byte data[], int dataLength) const {
    if (!available())
      return 0;

    int availableLength = regRead8(kRegICLENGTH);

    if (availableLength <= 0) {
      flushRead();
      return 0;
    }

    if (availableLength > dataLength)
      return -1;

    regRead(kRegICDATA, data, availableLength);

    int totalRead = availableLength;
    int missingPad = camctrlMissingFinalPadding(data, availableLength);
    if (missingPad > 0 && availableLength + missingPad <= dataLength && availableLength < 255) {
      data[availableLength] = regRead8(kRegICDATA + availableLength);
      totalRead = availableLength + missingPad;
    }

    regWrite8(kRegICARM, kRegICARM_ARM_Mask);

    return totalRead;
  }

  void SDICameraControl::flushRead() const { regWrite8(kRegICARM, kRegICARM_ARM_Mask); }

  int SDICameraControl::peekIncoming(byte data[], int dataLength) const
  {
    if (!shieldInitialized) {
      return 0;
    }

    int length = regRead8(kRegICLENGTH);
    if (length <= 0 || length > dataLength) {
      return 0;
    }

    regRead(kRegICDATA, data, length);

    int missingPad = camctrlMissingFinalPadding(data, length);
    if (missingPad > 0 && length + missingPad <= dataLength && length < 255) {
      data[length] = regRead8(kRegICDATA + length);
      length += missingPad;
    }

    return length;
  }

  bool SDICameraControl::availableForWrite() const { return (regRead8(kRegOCARM) & kRegOCARM_ARM_Mask) == 0; }

  void SDICameraControl::startBundle() {
    bundleActive = true;
  }

  void SDICameraControl::endBundle() {
    if(outputLength > 0) {
      write(outputBuffer, outputLength, true);
    }
    outputLength = 0;
    bundleActive = false;
  }

  void SDICameraControl::write(const byte data[], int dataLength, bool forceWrite) const {

    if(shieldInitialized) {
      if(!bundleActive || forceWrite) {
        if(momentaryOverride) setOverride(true);
        flushWrite();

        regWrite8(kRegOCLENGTH, dataLength);
        regWrite(kRegOCDATA, data, dataLength);

        regWrite8(kRegOCARM, kRegOCARM_ARM_Mask);
        if(momentaryOverride) setOverride(false);
      } else {
        if(outputLength + dataLength < 255) {
          memcpy(outputBuffer + outputLength, data, dataLength);
          outputLength += dataLength;
        } else {
          write(outputBuffer, outputLength, true);
          outputLength = 0;
        }
      }
    } else {
      memcpy(outputBuffer, data, dataLength);
      outputLength = dataLength;
    }
  }

  void SDICameraControl::flushWrite() const {
    while (!availableForWrite()) {
    }
  }

  void SDICameraControl::writeCommandVoid(byte camera, byte category, byte parameter) const {
    const uint8_t kHeaderLength = 4;
    const uint8_t kParamLength = 1;
    const uint8_t kPayloadLength = 4 + (kParamLength * 1);
    const uint8_t kPaddingLength = (kPayloadLength % 4) ? (4 - (kPayloadLength % 4)) : 0;

    byte payload[kHeaderLength + kPayloadLength + kPaddingLength] = {
                                                                     camera,
                                                                     kPayloadLength - 1,
                                                                     0,
                                                                     0,
                                                                     category,
                                                                     parameter,
                                                                     0,
                                                                     0,
                                                                     1, 0, 0, 0};

    write(payload);
  }

  void SDICameraControl::writeCommandBool(byte camera, byte category, byte parameter, byte operation, bool value) const {
    const uint8_t kHeaderLength = 4;
    const uint8_t kParamLength = 1;
    const uint8_t kPayloadLength = 4 + (kParamLength * 1);
    const uint8_t kPaddingLength = (kPayloadLength % 4) ? (4 - (kPayloadLength % 4)) : 0;

    byte payload[kHeaderLength + kPayloadLength + kPaddingLength] = {
                                                                     camera,
                                                                     kPayloadLength,
                                                                     0,
                                                                     0,
                                                                     category,
                                                                     parameter,
                                                                     0,
                                                                     operation,
                                                                     value, 0, 0, 0};

    write(payload);
  }

  void SDICameraControl::writeCommandUTF8(byte camera, byte category, byte parameter, byte operation, const char *string) const {
    const uint8_t kMaxStringLength = 64;

    const uint8_t kHeaderLength = 4;
    const uint8_t kParamLength = min(strlen(string), kMaxStringLength);
    const uint8_t kPayloadLength = 4 + (kParamLength * 1);
    const uint8_t kPaddingLength = (kPayloadLength % 4) ? (4 - (kPayloadLength % 4)) : 0;

    byte payload[kHeaderLength + (4 + kMaxStringLength) + 4] = {
        camera,
        kPayloadLength,
        0,
        0,
        category,
        parameter,
        5,
        operation,
    };

    strncpy((char *)&payload[kHeaderLength + 4], string, kParamLength);

    write(payload, kHeaderLength + kPayloadLength + kPaddingLength);
  }
}