/* -LICENSE-START-
 ** Copyright (c) 2016 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 ** 
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 ** 
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */

#pragma once

#include <stdint.h>
#include <Arduino.h>

#if defined(ARDUINO_NANO_MATTER)
#define BMD_SHIELD_SERIAL Serial1
#else
#define BMD_SHIELD_SERIAL Serial
#endif

namespace BMD
{
	template <typename T>
	class SerialPhysical : public T
	{
	public:
		// Inherits from T
		virtual void		begin();
		virtual uint32_t	regRead32(uint16_t address) const;
		virtual void		regWrite32(uint16_t address, uint32_t value) const;
		virtual uint16_t	regRead16(uint16_t address) const;
		virtual void		regWrite16(uint16_t address, uint16_t value) const;
		virtual uint8_t		regRead8(uint16_t address) const;
		virtual void		regWrite8(uint16_t address, uint8_t value) const;
		virtual void		regRead(uint16_t address, uint8_t values[], int length) const;
		virtual void		regWrite(uint16_t address, const uint8_t values[], int length) const;

	private:
		enum
		{
			kSync1Value = 0xDC,
			kSync2Value = 0x42,
			kSerialTimeoutMs = 100,
		};

		static void flushRx()
		{
			while (BMD_SHIELD_SERIAL.available())
				BMD_SHIELD_SERIAL.read();
		}

		static bool waitForBytes(int count, unsigned long timeoutMs = kSerialTimeoutMs)
		{
			unsigned long start = millis();
			while ((int)BMD_SHIELD_SERIAL.available() < count)
			{
				if (millis() - start > timeoutMs)
				{
					flushRx();
					return false;
				}
			}
			return true;
		}
	};

	template <typename T>
	void SerialPhysical<T>::begin()
	{
		BMD_SHIELD_SERIAL.begin(38400);
		flushRx();

		T::begin();
	}

	template <typename T>
	uint32_t SerialPhysical<T>::regRead32(uint16_t address) const
	{
		uint8_t regBytes[4] = {0, 0, 0, 0};

		flushRx();

		uint8_t request[] = {
			kSync1Value,
			kSync2Value,
			(uint8_t)(address & 0xFF),
			(uint8_t)(address >> 8),
			'R',
			4,
			0
		};
		BMD_SHIELD_SERIAL.write(request, sizeof(request));

		BMD_SHIELD_SERIAL.flush();

		if (!waitForBytes(4))
			return 0;

		regBytes[0] = BMD_SHIELD_SERIAL.read();
		regBytes[1] = BMD_SHIELD_SERIAL.read();
		regBytes[2] = BMD_SHIELD_SERIAL.read();
		regBytes[3] = BMD_SHIELD_SERIAL.read();

		return ((uint32_t)regBytes[3] << 24) | ((uint32_t)regBytes[2] << 16) | ((uint32_t)regBytes[1] << 8) | regBytes[0];
	}

	template <typename T>
	void SerialPhysical<T>::regWrite32(uint16_t address, uint32_t value) const
	{
		uint8_t request[] = {
			kSync1Value,
			kSync2Value,
			(uint8_t)(address & 0xFF),
			(uint8_t)(address >> 8),
			'W',
			4,
			0
		};
		BMD_SHIELD_SERIAL.write(request, sizeof(request));
		BMD_SHIELD_SERIAL.write(value >> 0);
		BMD_SHIELD_SERIAL.write(value >> 8);
		BMD_SHIELD_SERIAL.write(value >> 16);
		BMD_SHIELD_SERIAL.write(value >> 24);

		BMD_SHIELD_SERIAL.flush();
	}

	template <typename T>
	uint16_t SerialPhysical<T>::regRead16(uint16_t address) const
	{
		uint8_t regBytes[2] = {0, 0};

		flushRx();

		uint8_t request[] = {
			kSync1Value,
			kSync2Value,
			(uint8_t)(address & 0xFF),
			(uint8_t)(address >> 8),
			'R',
			2,
			0
		};
		BMD_SHIELD_SERIAL.write(request, sizeof(request));

		BMD_SHIELD_SERIAL.flush();

		if (!waitForBytes(2))
			return 0;

		regBytes[0] = BMD_SHIELD_SERIAL.read();
		regBytes[1] = BMD_SHIELD_SERIAL.read();

		return ((uint16_t)regBytes[1] << 8) | regBytes[0];
	}

	template <typename T>
	void SerialPhysical<T>::regWrite16(uint16_t address, uint16_t value) const
	{
		uint8_t request[] = {
			kSync1Value,
			kSync2Value,
			(uint8_t)(address & 0xFF),
			(uint8_t)(address >> 8),
			'W',
			2,
			0
		};
		BMD_SHIELD_SERIAL.write(request, sizeof(request));
		BMD_SHIELD_SERIAL.write(value >> 0);
		BMD_SHIELD_SERIAL.write(value >> 8);

		BMD_SHIELD_SERIAL.flush();
	}

	template <typename T>
	uint8_t	SerialPhysical<T>::regRead8(uint16_t address) const
	{
		flushRx();

		uint8_t request[] = {
			kSync1Value,
			kSync2Value,
			(uint8_t)(address & 0xFF),
			(uint8_t)(address >> 8),
			'R',
			1,
			0
		};
		BMD_SHIELD_SERIAL.write(request, sizeof(request));

		BMD_SHIELD_SERIAL.flush();

		if (!waitForBytes(1))
			return 0;

		return BMD_SHIELD_SERIAL.read();
	}

	template <typename T>
	void SerialPhysical<T>::regWrite8(uint16_t address, uint8_t value) const
	{
		uint8_t request[] = {
			kSync1Value,
			kSync2Value,
			(uint8_t)(address & 0xFF),
			(uint8_t)(address >> 8),
			'W',
			1,
			0
		};
		BMD_SHIELD_SERIAL.write(request, sizeof(request));
		BMD_SHIELD_SERIAL.write(value);

		BMD_SHIELD_SERIAL.flush();
	}

	template <typename T>
	void SerialPhysical<T>::regRead(uint16_t address, uint8_t values[], int length) const
	{
		if (length <= 0)
			return;

		flushRx();

		uint8_t request[] = {
			kSync1Value,
			kSync2Value,
			(uint8_t)(address & 0xFF),
			(uint8_t)(address >> 8),
			'R',
			(uint8_t)length,
			0
		};
		BMD_SHIELD_SERIAL.write(request, sizeof(request));

		BMD_SHIELD_SERIAL.flush();

		for (int i = 0; i < length; i++)
		{
			if (!waitForBytes(1))
			{
				for (int j = i; j < length; j++)
					values[j] = 0;
				return;
			}
			values[i] = BMD_SHIELD_SERIAL.read();
		}
	}

	template <typename T>
	void SerialPhysical<T>::regWrite(uint16_t address, const uint8_t values[], int length) const
	{
		uint8_t request[] = {
			kSync1Value,
			kSync2Value,
			(uint8_t)(address & 0xFF),
			(uint8_t)(address >> 8),
			'W',
			(uint8_t)length,
			0
		};
		BMD_SHIELD_SERIAL.write(request, sizeof(request));
		BMD_SHIELD_SERIAL.write(values, length);

		BMD_SHIELD_SERIAL.flush();
	}
}
